import { readFileSync, readdirSync, writeFileSync } from "node:fs";

/**
 * Serverless functions can't read supabase/migrations at runtime, so the SQL is
 * embedded in src/migrations.generated.ts. Run after adding a migration:
 *   npm run migrations:embed
 * (a unit test fails if the generated file is stale).
 */
export function renderMigrations(dir = "supabase/migrations"): string {
  const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
  const entries = files.map((f) => `  { name: ${JSON.stringify(f)}, sql: ${JSON.stringify(readFileSync(`${dir}/${f}`, "utf8"))} },`);
  return `// Generated by scripts/embed-migrations.ts from supabase/migrations. Do not edit.\nexport const MIGRATIONS: { name: string; sql: string }[] = [\n${entries.join("\n")}\n];\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync("src/migrations.generated.ts", renderMigrations());
  console.log("wrote src/migrations.generated.ts");
}
